### ISSUE TITLE
[WIP]Fallout4とCreationKitで始めるゲームクリエイト(二次裏May板)

### ISSUE THREAD

**Issue by akira1908jp** [hachiojipm/yapcasia-8oji-2016mid-timetable#28]
## 表記するお名前、SNSアカウント

akira1908jp
http://twitter.com/akira1908jp
## 概要
# **E&E (Enjoy and Exciting)**
## 要求トーク時間
# **LT(5min)**
## 想定聴講者層
# **無職**
# **童貞**
# **としあき**
## 録画や写真撮影と、その後の公開

NG(R-18などの内容が含むため)
## 日付の希望

両日問題無し 
## あなたは暴言などをしない常識を持っていて、このトークで人や法人を悲しませたり怒らせたりせず、平たく言ってネット等でダメな方向に炎上するような行動は慎むことを誓えますか？

I Accept The Agree
## お知らせとなる #1 お知らせスレをSubscribeするなどしてちゃんと読みますか？

Subscribed

**Comment by uzulla** [comment]
会場では18歳未満（あるいは成人）の確認や、きちんとした入室ブロックをおこなうことは難しいです。
（撮影禁止は問題ないのですが）18歳未満に不適切な要素を削減することはできますか？

**Comment by akira1908jp** [comment]
> 会場では18歳未満（あるいは成人）の確認や、きちんとした入室ブロックをおこなうことは難しいです。
> （撮影禁止は問題ないのですが）18歳未満の要素を削減することはできますか？

出来る限りはしますが、表現上の描写のため部分的な修正など表示は不可能でしょうか。

**Comment by uzulla** [comment]
繰り返しになりますが、年齢レーティングが存在するトークは今回は発表いただけません。
なので、「できるかぎりやって一部アウト」はやはりアウトです。

> 表現上の描写のため部分的な修正など表示は不可能でしょうか。

この一文だけでは判断ができませんが、「このトークで人や法人を悲しませたり怒らせたりせず、平たく言ってネット等でダメな方向に炎上するような行動は慎むことを誓えますか？」というところにひっかからないか十分に検討いただく必要があるとおもいます。

以下のSlackやTwitterなどで私にDMで「具体的に」こういう表現や画面／画像をしたい等、ご相談ください。スライドの事前確認も致します。

https://yapc8oji-slack-auto-invitation-form.arukascloud.io/

**Comment by uzulla** [comment]
akira1908jpさんとお話をして、こちらのトーク応募はキャンセルするといただきましたので代理でクローズ致します。
