### ISSUE TITLE
XcodeのPlaygroundと同じことをC#でやってみる

### ISSUE THREAD

**Issue by ytabuchi** [hachiojipm/yapcasia-8oji-2016mid-timetable#49]
## 表記するお名前、SNSアカウント

ytabuchi
http://twitter.com/ytabuchi
## 概要

XcodeにはPlaygroundという、ちょっとしたSwiftのコードを即時実行して試せる機能があります。C# でも同様の機能を実現したいと思いませんか？Workbooksというツールで遊んでみましたので共有します。
## 要求トーク時間

C/11:00/20min
## 想定聴講者層

初級者
C# や iOS/Android アプリ開発を学びたい方
## 録画や写真撮影と、その後の公開

OK
## 日付の希望

両日問題無し
## あなたは暴言などをしない常識を持っていて、このトークで人や法人を悲しませたり怒らせたりせず、平たく言ってネット等でダメな方向に炎上するような行動は慎むことを誓えますか？

誓います。
## お知らせとなる #1 お知らせスレをSubscribeするなどしてちゃんと読みますか？

読みます。

**Comment by uzulla** [comment]
お世話になっております、ヤパチー運営です。

今回登壇者の方も、対象の日付で登壇者枠でのConnpass登録をお願いしております。
- http://connpass.com/event/33562/

当方の見落としでしたら申し訳ございませんが、当日の登壇者登録がまだなされていないようでしたので、是非ご確認下さい。
（もし、Github名とConnpass上の名前が異なる名前の場合には、お教え下さい）

なにか質問やご意見などございましたらば、御連絡下さい。

**Comment by ytabuchi** [comment]
失礼いたしました！レギュラー登壇者枠というので申し込みしました！

**Comment by uzulla** [comment]
動画を公開いたしました！
https://www.youtube.com/watch?v=2LHWM7CmP6g

**Comment by ytabuchi** [comment]
ありがとうございます！拡散させていただきました(^^)
