### ISSUE TITLE
エンジニアやエンジニアを目指している人が見るべきアニメ

### ISSUE THREAD

**Issue by stefafafan** [hachiojipm/yapcasia-8oji-2016mid-timetable#50]
## 表記するお名前、SNSアカウント

すてにゃん
https://twitter.com/stefafafan
## 概要

アニメといえば萌え系だったりハーレムものだったりを想像する人も多いと思います（実際そういう作品は沢山あります）が、もっとギーク向けのものやエンジニアの興味をひく作品も多数あると思います。普段からアニメを全くみていない方もこれを機会にいくつかみてみてはどうでしょうか。
## 要求トーク時間

5 min
## 想定聴講者層

アニメに興味を持っている方
## 録画や写真撮影と、その後の公開

OKです！
## 日付の希望

両日問題無し
## あなたは暴言などをしない常識を持っていて、このトークで人や法人を悲しませたり怒らせたりせず、平たく言ってネット等でダメな方向に炎上するような行動は慎むことを誓えますか？

誓います。
## お知らせとなる #1 お知らせスレをSubscribeするなどしてちゃんと読みますか？

Subscribeしました！

**Comment by uzulla** [comment]
ご応募ありがとうございます、ヤパチー運営です。

こちらのトークはアニメの紹介をおこなわれるとのことですが、アニメのスクリーンショットなどの画像などを表示しますか？

**Comment by stefafafan** [comment]
連絡ありがとうございます。

アニメの画像などを見せたい気持ちもありますが、著作権的に問題あると思うので出さない方向でやろうと思います。

**Comment by uzulla** [comment]
すみません、すでに交渉済みですが、7/3A部屋から7/2A部屋に変更させていただきました。
お手数ですが、connpass登録変更お願いいたします。

**Comment by stefafafan** [comment]
変更について、了解いたしました。
connpassのほうは現在両日スタッフ枠として登録しているのですが（B部屋のお手伝いすることに現在なっています）、このままで大丈夫でしょうか？

**Comment by uzulla** [comment]
あ、そうですね、スタッフ枠が最強（？）なので、そのままでOKです。

**Comment by uzulla** [comment]
タイムテーブルにも反映いたしました、ご確認ください。

**Comment by stefafafan** [comment]
資料公開しました。
https://speakerdeck.com/stefafafan/anime-that-i-recommend-for-engineers-to-watch
