### ISSUE TITLE
このRDBについて私は驚くべき闇を見つけたがそこを発表するにはネットは怖すぎる

### ISSUE THREAD

**Issue by soudai** [hachiojipm/yapcasia-8oji-2016mid-timetable#57]
## 表記するお名前、SNSアカウント

そーだい
http://twitter.com/soudai1025
## 概要

RDBでハマったつらい想い出を淡々と伝える

・MySQL
・PostgreSQL

など。
## 要求トーク時間

B/13:00/50min
## 想定聴講者層

中級者
RDBを使ったサービス使っている人
RDBにちょっとでも興味がある人
## 録画や写真撮影と、その後の公開

OK
## 日付の希望

両日問題無し
## あなたは暴言などをしない常識を持っていて、このトークで人や法人を悲しませたり怒らせたりせず、平たく言ってネット等でダメな方向に炎上するような行動は慎むことを誓えますか？

誓います(///
## お知らせとなる #1 お知らせスレをSubscribeするなどしてちゃんと読みますか？

正座して読みます
## 登壇資料はこちら

https://speakerdeck.com/soudai/kofalserdbnituitesi-hajing-kuhekian-wojian-tuketakasokowofa-biao-surunihanetutohabu-sukiru

**Comment by uzulla** [comment]
@soudai さん
もし違う場合には申し訳ございませんが、登壇時にマウスをおわすれになりませんでしたでしょうか？

**Comment by soudai** [comment]
@uzulla 
やぱちーのTOPに書いてあったマウスの件ですよね？
私はマウスを持って来てないので違います。
ご心配ありがとうございます。

**Comment by uzulla** [comment]
動画を公開しました！
https://www.youtube.com/watch?v=0ilRNXo4faA
