### ISSUE TITLE
MySQLとPostgresSQLがキャッキャウフフする

### ISSUE THREAD

**Issue by soudai** [hachiojipm/yapcasia-8oji-2016mid-timetable#85]
## 表記するお名前、SNSアカウント

そーだい
http://twitter.com/soudai1025

yoku0825
http://twitter.com/yoku0825
## 概要

そーだいなるディスカッション。
訳）PostgresSQLとMySQLのエンジニアがその場でテーマを決めてディスカッション。
### テーマ候補
- SQLアンチパターン
- DBにstatusを持たすとき
- DBエンジニアになるには？

などなど。
その場で挙手制でテーマを募集するかもしれません。
## 要求トーク時間

D/15:00/50min
## 想定聴講者層

初心者から中級者くらいまで
RDBに興味がある人全般
## 録画や写真撮影と、その後の公開

OK 
## 日付の希望

両日問題無し
## あなたは暴言などをしない常識を持っていて、このトークで人や法人を悲しませたり怒らせたりせず、平たく言ってネット等でダメな方向に炎上するような行動は慎むことを誓えますか？

Yes we can!!
## お知らせとなる #1 お知らせスレをSubscribeするなどしてちゃんと読みますか？

I can do it!!

**Comment by yoku0825** [comment]
パネラーの他のセッション
- soudai1025
  - #54 
  - #57 
- yoku0825
  - #14 
  - #41

**Comment by yoku0825** [comment]
## 日付の希望

できれば 7/2(土)、 #14 , #41 と同じ日希望（両日行くのが難しいかもなので）
