### ISSUE TITLE
アンカンファレンストラック

### ISSUE THREAD

**Issue by myfinder** [hachiojipm/yapcasia-8oji-2016mid-timetable#89]
## 表記するお名前、SNSアカウント

まいんだー
http://twitter.com/myfinder
## 概要

トークが大量に集まって、Rejectも可能性が出てきたのもあり、本編トラックとは別にアンカンファレンス会場を都合して、その場で参加者がいろいろと発表したり議論したりする場があってもよいと思いました。
会場の都合は要調整ですが、希望が多ければ対応します。

**アンカンファレンスとは↓**
http://d.hatena.ne.jp/keyword/%A5%A2%A5%F3%A5%AB%A5%F3%A5%D5%A5%A1%A5%EC%A5%F3%A5%B9
## 要求トーク時間

2日間
## 想定聴講者層

誰でもOK
## 録画や写真撮影と、その後の公開

無理そう
## 日付の希望

両日通しで
## あなたは暴言などをしない常識を持っていて、このトークで人や法人を悲しませたり怒らせたりせず、平たく言ってネット等でダメな方向に炎上するような行動は慎むことを誓えますか？

YES
## お知らせとなる #1 お知らせスレをSubscribeするなどしてちゃんと読みますか？

YES

**Comment by uzulla** [comment]
これは「トーク応募」ではなく、新しく部屋（やイベント）を増やす提案だとおもいますが、

そのような新しい何かの提案であれば、立てるのは以下のイベント全体repoのISSUEがふさわしいと思いますがどうでしょうか。
https://github.com/hachiojipm/yapcasia-8oji-2016mid/

ただ、こちらのrepoのほうが人目に触れるので、「このスレで参加者側の人をつのり、議論していきたい！」ということであればここでもよいです。

いずれにしても、「トークではない、新しいトラック作成の提案である」となっているとみなさん解りやすいのでは。
たとえば、撮影や同意については消して、どういうことをやる！というのを具体的に書いて良いのでは。
あとは、最初の１行に「アンカンファレンス希望者は＋１して！」って書くとか、タイトルに「ご意見募集」と書くとか。

**Comment by myfinder** [comment]
確かに。であれば本件はいったんcloseします
