### ISSUE TITLE
AIって言葉流行っているけど、実際どう組み込むのさ？

### ISSUE THREAD

**Issue by masa-fleet** [hachiojipm/yapcasia-8oji-2016mid-timetable#90]
## 表記するお名前、SNSアカウント

kumasayuki
https://twitter.com/masota0517
## 概要

AI/Deep Learning というキーワードで夢は広がり「AI を取り入れた製品を開発しよう!」と盛り上がる事業部門・企画部門！そのとき開発者はどうする！！？
次回新世紀エバンジェリスト: AI 襲来

と中二臭あふれる感じの概要にしましたが、まじめに書くと以下のような感じです。トークは中２でテックはまじめにやります。
- 案件で実際に実装するときの選択方式
- Cognitive Service を組み込んでAI的機能を実装するときのノウハウ/アーキテクチャ共有
## 要求トーク時間

A/14:00/30min
## 想定聴講者層

中級者
AIって言葉流行ってるけど実際どう使うのさ？という人
## 録画や写真撮影と、その後の公開

写真撮影は大丈夫です。
録画については、Power BI を社内でどう活用しているか？という部分だけ削除いただけないでしょうか。個別の削除が難しい場合には、動画を非公開としていただきますと幸いです。
## 日付の希望

日曜日の午後か、土曜日でお願いします！
## あなたは暴言などをしない常識を持っていて、このトークで人や法人を悲しませたり怒らせたりせず、平たく言ってネット等でダメな方向に炎上するような行動は慎むことを誓えますか？

はい！（真顔
## お知らせとなる #1 お知らせスレをSubscribeするなどしてちゃんと読みますか？

はい！

**Comment by masa-fleet** [comment]
@uzulla さん、タイムテーブル確認しました。
ご指定いただきました時間帯で大丈夫です！よろしくお願いします。

**Comment by uzulla** [comment]
お世話になっております、ヤパチー運営です。

今回登壇者の方も、対象の日付で「登壇者枠」でのConnpass登録をお願いしております。
- http://connpass.com/event/33563/

当方の見落としでしたら申し訳ございませんが、当日の登壇者登録をまだいただいていないご様子でしたので、是非ご確認下さい。
（もし、Github名とConnpass上の名前が異なる名前の場合には、お教え下さい）

なにか質問やご意見などございましたらば、御連絡下さい。

**Comment by uzulla** [comment]
@NT-D さん
お世話になっております、ヤパチー運営です。
ご応募いただいたトークは7/3(二日目)で採択させていただきましたが、まだ

http://connpass.com/event/33563/

にて、レギュラートーク枠の参加登録をいただいていないように見受けられます。お忙しい所大変恐縮ですが、お早めにご登録頂ければ幸いです。
もし登録済みでしたらば申し訳ございません、お名前やアイコンがGithubのものと違う場合にはご指摘ください。

**Comment by masa-fleet** [comment]
@uzulla さん
すみません、動画公開の方針について下記のとおり変更させてください。

[変更方針]
写真撮影は大丈夫です。
 録画については、Power BI を社内でどう活用しているか？という部分だけ削除いただけないでしょうか。個別の削除が難しい場合には、動画を非公開としていただきますと幸いです。

**Comment by uzulla** [comment]
上記了解いたしました、一部の切り取りが可能か後日確認してみます。
御連絡ありがとうございました。
